### GENERAL SETTINGS ###

# Site settings
title: OSGeo-PT
description: "Uma bússola para o guiar no mundo do open source."
baseurl: "" #"/siteosgeopt"
url: "http://osgeopt.pt"  #"http://dncpax.github.io" #

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00B16A" 
  primary_rgb: "0,177,106" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452"
  link: "#428bca"
  link_hover: "#C8F7C5"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: http://facebook.com/osgeopt
  - title: github
    url: http://github.com/osgeo-pt
  - title: twitter
    url: https://twitter.com/OSGeoPT
  - title: google-plus
    url: http://google.com/+OsgeoptPt1
  - title: 
    url: 
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    -
    -
    -
email:
tel:


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
    
# Clients information. Shown on Home and About pages.
clients:
  - name: O seu logo
    img: parceiro01.png
  - name: O seu logo
    img: parceiro01.png
  - name: O seu logo
    img: parceiro01.png
  - name: O seu logo
    img: parceiro01.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "A OSGeo-PT é uma associação sem fins lucrativos com o objectivo de suportar e promover o desenvolvimento e a utilização de tecnologias, padrões e dados Livres."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "“In open source, we feel strongly that to really do something well, you have to get a lot of people involved.”"
    author: Linus Trovalds
    position: ...
    message: "“Open source isn’t about saving money, it’s about doing more stuff, and getting incremental innovation with the finite budget you have.”"
    author:  Jim Whitehurst,
    position: CEO, Red Hat
  
